# Frequency of issuance of effects in ticks (default: 100 (5 seconds))
frequency: 100

# Effect duration in ticks (default: 432000 (6 hours))
effectDuration: 432000

# Does step affects money cost of new level (default: false)
stepAffectsMoney: false

# Does step affects experience bottle cost of new level (default: true)
stepAffectsBottles: true