name: BByaPlugin_GuildsClans
main: ru.OcelotJungle.BByaPlugin_GC.Main
version: 1
description: Processing of Guilds and Clans on server
commands:
  bbyaplugingc:
    description: main command
    usage: /bbyaplugingc help
    permission: op
    aliases: [gc]